github:
  owner: ''
  repo: daily-paper-reader
arxiv_paper_setting:
  mode: standard
  days_window: 3
  docs_dir: docs
subscriptions:
  keywords:
    - keyword: large neighborhood search
      tag: LNS
    - keyword: â€ªEvolution of Heuristics
      tag: EOH
    - keyword: Efficient Automatic Algorithm
      tag: EAA
  llm_queries: []
  tracked_papers: []
